language: objective-c
osx_image: xcode9
xcode_project: PDFGenerator.xcodeproj
xcode_scheme: PDFGenerator
env:
  global:
  - DESTINATION="platform=iOS Simulator,name=iPhone 8"
  - FRAMEWORK_NAME=PDFGenerator
branches:
  only:
  - master
  - "/bugfix.*/"
  - "/^develop.*/"
  - "/^v?[0-9\\.]+/"

before_install:
  - export IOS_SIMULATOR_UDID=$(instruments -s devices | grep "$ios_device ($ios_version)" | sed -E 's/.*\[([0-9A-F-]+)\].*/\1/g')
  - echo "Prelaunching iOS simulator $IOS_SIMULATOR_UDID"
  - open -a "simulator" --args -CurrentDeviceUDID $IOS_SIMULATOR_UDID

script:
- if [[ "$JOB" == "Xcode7.3" ]]; then pod lib lint; fi
- set -o pipefail
- xcodebuild test -project "$TRAVIS_XCODE_PROJECT" -scheme "$TRAVIS_XCODE_SCHEME" -sdk iphonesimulator -destination "$DESTINATION" | xcpretty -c
after_success:
  - bash <(curl -s https://codecov.io/bash)
before_deploy:
- carthage build --no-skip-current
- carthage archive "$FRAMEWORK_NAME"
